# Generated by Django 6.1 on 2026-08-26 20:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quotation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client_name', models.CharField(max_length=255)),
                ('company_name', models.CharField(blank=True, max_length=255)),
                ('phone', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('location', models.CharField(max_length=255)),
                ('project_description', models.TextField()),
                ('preferred_project_date', models.DateField(blank=True, null=True)),
                ('budget_range', models.CharField(blank=True, max_length=255)),
                ('additional_comments', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('new', 'New'), ('reviewing', 'Reviewing'), ('contacted', 'Contacted'), ('quoted', 'Quoted'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('completed', 'Completed')], default='new', max_length=20)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='quotations', to='services.service')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
