# Generated by Django 6.1 on 2026-08-26 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('tagline', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField()),
                ('mission', models.TextField(blank=True)),
                ('vision', models.TextField(blank=True)),
                ('values', models.TextField(blank=True)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('whatsapp', models.CharField(blank=True, max_length=50)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('address', models.TextField(blank=True)),
                ('google_maps_url', models.URLField(blank=True)),
                ('facebook_url', models.URLField(blank=True)),
                ('linkedin_url', models.URLField(blank=True)),
                ('instagram_url', models.URLField(blank=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='company/')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
